### PR TITLE
fix: Fix file type column

### LINKED ISSUE #2004: Replace "file" by "mime-type" in Media manager list view
### Context / Problem to solve / Design
It is impossible to know the type of a file when browsing the medias in list view, which is really problematic, The column tyoe displays File or Folder and nothing else. Hence it is useless.

### Story
As an editor
I want to see the real type of my files in list views

## Testable scenarios

**Setup**
Given I'm in jContent/assets

**Case 1**
When I upload an image document
Then it's type (jpg, png, webp...) is displayed in the type column

**Case N**
When I click on the column header
Then the list is sorted alphabeticaly by type

### Test Strategy
Cypress tests?

### Labels 
En: 
Fr: 
De:

### PR DESCRIPTION
**Pull request by AKarmanov**
### Description
Fix file type column and display mime type for files.

#### Source code
- [ ] I've shared and documented any breaking change
- [ ] I've reviewed and updated the jahia-depends

#### Tests
- [ ] I've provided Unit and/or Integration Tests
- [ ] I've updated the parent issue with required manual validations

> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)

### CODE REVIEW

File: src/javascript/JContent/ContentRoute/ContentLayout/ContentTable/reactTable/components/cells/CellType.jsx [hunk 1]
```diff
@@ -3,14 +3,21 @@ import PropTypes from 'prop-types';
 import {TableBodyCell, Typography} from '@jahia/moonstone';
 
 export const CellType = ({value, cell, column, row}) => {
+    const node = row.original;
+    let type = value;
+
+    if (node.primaryNodeType.name === 'jnt:file') {
+        type = node.content?.mimeType?.value;
```
Comment (gflores-jahia) [inline src/javascript/JContent/ContentRoute/ContentLayout/ContentTable/reactTable/components/cells/CellType.jsx:10]: maybe default back to `value` if mimeType.value doesn't exist?

**Review by gflores-jahia — COMMENTED** [review]
added small clarification

**Review by gflores-jahia — APPROVED** [review]
