### PR TITLE
fix: Update selection styles

### LINKED ISSUE #1554: BACKLOG-23617 - Simplify the styling of selected content in Page Builder
> Imported from Jira, on Thu Jan 30, 2025
> Issue: [BACKLOG-23617](https://jira.jahia.org/browse/BACKLOG-23617) in project: DX BACKLOG
> Priority: Major Type: Story
> Reporter: @ffffffelix (Félix Vallé)
> Assignee: _None found in Jira, making reporter the assignee in GitHub_
> Created: Thu Jan 30, 2025, last updated: Thu Jan 30, 2025
> Status: Open
>
> **Links**:
> - relates to: [BACKLOG-23586 - Clarification: de-selection in page builder / selection behaviour](https://github.com/Jahia/jcontent/issues/1565) *[[JIRA](https://jira.jahia.org/browse/BACKLOG-23586)]* (Open)
>

**As a** Editor
**I want to** clear design 
**In order to** understand which element is selected
### Testable scenarios

**Selection**

**When** an element is selected:
* We **don't** display the header
* We **don't** display the footer (even on hover)
* We **only** display a plain border with dark blue (`--color-accent_dark`) on selected items

 

**Hovering**

**Given** an element is selected
**When** I am hovering over another item
**Then** the hovered item is highlighted with a dashed blue border (same style than I am hovering content item without selection)
### Test Strategy

### PR DESCRIPTION
**Pull request by AKarmanov**
## Description

Update selection styles

### CODE REVIEW

File: src/javascript/JContent/EditFrame/Box.jsx [hunk 1]
```diff
@@ -17,15 +17,15 @@ const reposition = function (element, currentOffset, setCurrentOffset, isHeaderD
     }
 };
 
-const processCustomBoxConfigIfExists = (node, type) => {
+const processCustomBoxConfigIfExists = (node, type, isSelected) => {
```
Comment (gflores-jahia) [inline src/javascript/JContent/EditFrame/Box.jsx:20]: should this also say `isSomethingSelected` vs `isSelected` ?

**Review by gflores-jahia — COMMENTED** [review]
Sorry minor request (and ok to say no), but I see that we already have `isAnythingDragging`, so wondering if we can switch to `isAnythingSelected` to at least keep it consistent.

I also have a comment on the method part as well.

**Review by gflores-jahia — APPROVED** [review]
