### PR TITLE
fix: Keep create button styling for empty elements

### LINKED ISSUE #1429: Child node button not visible when content is selected
### Environment and versions used

jahia 8.2 latest, jcontent 3.2 snap

### Steps to reproduce

1. install industrial : curl -sSL https://raw.githubusercontent.com/jahia/industrial/refs/heads/main/provisioning/industrial.sh | bash -s -- -h http://localhost:8080 -u root:root1234
2. create a industrial website from prepack
3. create a new page with the **free** template
4. add a new halfblock content in the empty area

### Current Behavior

from **Page composer** in 8.1.7.2 the button to add child node are accessible when the halfblock content is selected
**Hover** :

Image

**Selected** :

Image

**In Page builder** 
**Hover** :

Image

**Selected** :

Image

So when you select the parent of childnode the button to add the child disappears 

### Desired Behavior

The button must be accessible anytime

### PR DESCRIPTION
**Pull request by gflores-jahia**
## Description

- Fix bug on displaying create buttons for targeted child nodes
- Keep regular styling for empty components

### CODE REVIEW

File: src/javascript/JContent/EditFrame/Create.jsx [hunk 1]
```diff
@@ -42,8 +42,11 @@ function reposition(element, currentOffset, setCurrentOffset) {
     }
 }
 
-const useElemAttributes = ({element, parent, isInsertionPoint}) => {
-    const nodePath = (element.getAttribute('path') === '*' || isInsertionPoint) ? null : element.getAttribute('path');
+const useElemAttributes = ({element, parent}) => {
+    const isInsertionPoint = element.getAttribute('type') !== 'placeholder';
```
Comment (gflores-jahia) [inline src/javascript/JContent/EditFrame/Create.jsx:46]: Need to check here if insertionPoint is an original create button or not, otherwise it breaks create button for specific child nodes.

**Review by AKarmanov — DISMISSED** [review]

**Review by AKarmanov — APPROVED** [review]
